## Muhammad Fikri
## 2109106010
## postets 2 analysis data
## kecerdasan buatan

In [37]:
import pandas as pd
import numpy as np

df =pd.read_csv('Weather.csv')

#### masukkan dalam dictionary

In [18]:
dict = {
    'attributes': 0,
    'null_attributes': 0,
    'object_attributes': 0,
    'total_records': 0,
    'number_attributes':0
}

In [19]:
dict['attributes'] = list(df.columns.values)
dict['null_attributes'] = list(df.loc[:, df.isnull().any()].columns)
dict['object_attributes'] = list(df.select_dtypes(['object']).columns)
dict['total_records'] = df.shape[0]
dict['number_attributes'] = list(df.select_dtypes(['float64', 'int64']).columns)

#### menampilkan jumlah record

In [20]:
dict['total_records']

10481

#### menampilkan nama attriebutes

In [21]:
dict['attributes']

['pickup_datetime',
 'tempm',
 'tempi',
 'dewptm',
 'dewpti',
 'hum',
 'wspdm',
 'wspdi',
 'wgustm',
 'wgusti',
 'wdird',
 'wdire',
 'vism',
 'visi',
 'pressurem',
 'pressurei',
 'windchillm',
 'windchilli',
 'heatindexm',
 'heatindexi',
 'precipm',
 'precipi',
 'conds',
 'icon',
 'fog',
 'rain',
 'snow',
 'hail',
 'thunder',
 'tornado']

#### menampilkan jumlah atributes

In [22]:
len(dict['attributes'])

30

#### jumlah atribute tipe objek

In [24]:
len(dict['object_attributes'])

4

#### jumlah atribut tipe angka

In [25]:
len(dict['number_attributes'])

26

#### jumlah atribut yang memiliki nilai null

In [ ]:
len(dict['null_attributes'])

19

##### Tampilkan rata-rata, standar deviasi, nilai minimum, nilai maksimum, Q1, Q2, dan Q3 dari attribute bertipe angka.

Q1 = 25%, Q2= 50%, Q3=75%

In [29]:
 df.describe()

,tempm,tempi,dewptm,dewpti,hum,wspdm,wspdi,wgustm,wgusti,wdird,...,heatindexm,heatindexi,precipm,precipi,fog,rain,snow,hail,thunder,tornado
count,10476.000000,10476.000000,10476.000000,10476.000000,10476.000000,9744.000000,9744.000000,1876.000000,1876.000000,10481.000000,...,837.000000,837.000000,1706.000000,1706.000000,10481.000000,10481.000000,10481.000000,10481.0,10481.0,10481.0
mean,13.705622,56.670151,5.957961,42.723759,62.685949,8.690004,5.410324,34.969243,21.744296,80.298636,...,30.370012,86.670370,1.343728,0.052503,0.006774,0.093598,0.021754,0.0,0.0,0.0
std,9.521071,17.138025,10.629692,19.133455,20.000169,6.311644,3.925301,7.561813,4.694460,115.933469,...,2.824935,5.083867,2.295156,0.090534,0.082030,0.291282,0.145885,0.0,0.0,0.0
min,-18.300000,-0.900000,-28.300000,-18.900000,9.000000,0.000000,0.000000,25.900000,16.100000,0.000000,...,26.600000,79.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
25%,6.100000,43.000000,-2.200000,28.000000,47.000000,5.600000,3.500000,29.600000,18.400000,0.000000,...,28.300000,83.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
50%,13.300000,55.900000,6.700000,44.100000,61.000000,7.400000,4.600000,33.300000,20.700000,0.000000,...,29.700000,85.400000,0.500000,0.020000,0.000000,0.000000,0.000000,0.0,0.0,0.0
75%,21.700000,71.100000,15.000000,59.000000,81.000000,13.000000,8.100000,38.900000,24.200000,160.000000,...,31.800000,89.200000,1.500000,0.060000,0.000000,0.000000,0.000000,0.0,0.0,0.0
max,35.600000,96.100000,25.600000,78.100000,100.000000,137.000000,85.200000,72.200000,44.900000,360.000000,...,43.300000,109.900000,20.600000,0.810000,1.000000,1.000000,1.000000,0.0,0.0,0.0

#### tampilkan nilai korelasi

In [30]:
df.corr()

,tempm,tempi,dewptm,dewpti,hum,wspdm,wspdi,wgustm,wgusti,wdird,...,heatindexm,heatindexi,precipm,precipi,fog,rain,snow,hail,thunder,tornado
tempm,1.000000,0.999999,0.875999,0.875997,0.073267,-0.301371,-0.301287,-0.252228,-0.252251,-0.206499,...,0.832110,0.832048,0.196163,0.196034,-0.067884,-0.001625,-0.233106,NaN,NaN,NaN
tempi,0.999999,1.000000,0.875990,0.875989,0.073251,-0.301376,-0.301292,-0.252172,-0.252196,-0.206539,...,0.832008,0.831954,0.196240,0.196111,-0.067828,-0.001612,-0.233036,NaN,NaN,NaN
dewptm,0.875999,0.875990,1.000000,0.999999,0.536471,-0.305487,-0.305415,-0.242696,-0.242736,-0.243708,...,0.583623,0.583767,0.241634,0.241351,-0.013159,0.177566,-0.139850,NaN,NaN,NaN
dewpti,0.875997,0.875989,0.999999,1.000000,0.536467,-0.305489,-0.305417,-0.242792,-0.242831,-0.243702,...,0.583258,0.583410,0.241555,0.241272,-0.013189,0.177577,-0.139848,NaN,NaN,NaN
hum,0.073267,0.073251,0.536471,0.536467,1.000000,-0.096812,-0.096819,-0.055264,-0.055324,-0.151609,...,0.124662,0.124800,0.300419,0.299651,0.109794,0.422973,0.141530,NaN,NaN,NaN
wspdm,-0.301371,-0.301376,-0.305487,-0.305489,-0.096812,1.000000,0.999997,0.595539,0.595382,0.454223,...,0.102006,0.101882,-0.073564,-0.072992,0.125769,0.048746,0.126969,NaN,NaN,NaN
wspdi,-0.301287,-0.301292,-0.305415,-0.305417,-0.096819,0.999997,1.000000,0.595553,0.595396,0.454394,...,0.101807,0.101685,-0.073591,-0.073018,0.125720,0.048730,0.126922,NaN,NaN,NaN
wgustm,-0.252228,-0.252172,-0.242696,-0.242792,-0.055264,0.595539,0.595553,1.000000,0.999994,0.228666,...,-0.157222,-0.156700,0.020180,0.020703,0.209301,0.002986,0.144530,NaN,NaN,NaN
wgusti,-0.252251,-0.252196,-0.242736,-0.242831,-0.055324,0.595382,0.595396,0.999994,1.000000,0.228706,...,-0.156373,-0.155852,0.020242,0.020762,0.209146,0.003023,0.144448,NaN,NaN,NaN
wdird,-0.206499,-0.206539,-0.243708,-0.243702,-0.151609,0.454223,0.454394,0.228666,0.228706,1.000000,...,0.033318,0.033074,-0.043885,-0.043914,-0.007738,-0.029564,-0.023572,NaN,NaN,NaN
vism,-0.011005,-0.011032,-0.291454,-0.291437,-0.660521,-0.026484,-0.026442,-0.115362,-0.115333,0.108001,...,-0.310759,-0.311040,-0.261607,-0.261533,-0.247206,-0.618865,-0.381952,NaN,NaN,NaN
visi,-0.011899,-0.011926,-0.292374,-0.292356,-0.660818,-0.026260,-0.026217,-0.115790,-0.115762,0.108212,...,-0.311448,-0.311729,-0.262449,-0.262378,-0.248489,-0.618253,-0.382190,NaN,NaN,NaN
pressurem,-0.151441,-0.151425,-0.250890,-0.250818,-0.272717,-0.135363,-0.135340,-0.207737,-0.207724,-0.106230,...,-0.189223,-0.189084,-0.064341,-0.064493,-0.065664,-0.186963,-0.027674,NaN,NaN,NaN
pressurei,-0.151713,-0.151698,-0.251210,-0.251139,-0.272885,-0.135091,-0.135068,-0.207634,-0.207621,-0.106067,...,-0.189123,-0.188988,-0.064750,-0.064901,-0.065677,-0.186999,-0.027589,NaN,NaN,NaN
windchillm,0.978091,0.978060,0.722964,0.723000,0.198908,-0.336591,-0.336517,-0.252451,-0.252642,-0.144868,...,NaN,NaN,0.023565,0.022755,-0.169827,0.167366,-0.260052,NaN,NaN,NaN
windchilli,0.978057,0.978023,0.722998,0.723035,0.199001,-0.336689,-0.336616,-0.252339,-0.252530,-0.144907,...,NaN,NaN,0.023598,0.022778,-0.169790,0.167452,-0.260104,NaN,NaN,NaN
heatindexm,0.832110,0.832008,0.583623,0.583258,0.124662,0.102006,0.101807,-0.157222,-0.156373,0.033318,...,1.000000,0.999930,-0.105379,-0.095964,NaN,0.030424,NaN,NaN,NaN,NaN
heatindexi,0.832048,0.831954,0.583767,0.583410,0.124800,0.101882,0.101685,-0.156700,-0.155852,0.033074,...,0.999930,1.000000,-0.100830,-0.091347,NaN,0.030831,NaN,NaN,NaN,NaN
precipm,0.196163,0.196240,0.241634,0.241555,0.300419,-0.073564,-0.073591,0.020180,0.020242,-0.043885,...,-0.105379,-0.100830,1.000000,0.999937,0.205319,0.248214,-0.114020,NaN,NaN,NaN
precipi,0.196034,0.196111,0.241351,0.241272,0.299651,-0.072992,-0.073018,0.020703,0.020762,-0.043914,...,-0.095964,-0.091347,0.999937,1.000000,0.205912,0.248853,-0.114022,NaN,NaN,NaN
fog,-0.067884,-0.067828,-0.013159,-0.013189,0.109794,0.125769,0.125720,0.209301,0.209146,-0.007738,...,NaN,NaN,0.205319,0.205912,1.000000,0.081286,0.306629,NaN,NaN,NaN
rain,-0.001625,-0.001612,0.177566,0.177577,0.422973,0.048746,0.048730,0.002986,0.003023,-0.029564,...,0.030424,0.030831,0.248214,0.248853,0.081286,1.000000,-0.047920,NaN,NaN,NaN
snow,-0.233106,-0.233036,-0.139850,-0.139848,0.141530,0.126969,0.126922,0.144530,0.144448,-0.023572,...,NaN,NaN,-0.114020,-0.114022,0.306629,-0.047920,1.000000,NaN,NaN,NaN
hail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
thunder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tornado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Ubah nilai salah satu attribute bertipe angka menjadi desimal 3 angka dibelakang koma

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10481 entries, 0 to 10480
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup_datetime  10481 non-null  object
 1   tempm            10476 non-null  float64
 2   tempi            10476 non-null  float64
 3   dewptm           10476 non-null  float64
 4   dewpti           10476 non-null  float64
 5   hum              10476 non-null  float64
 6   wspdm            9744 non-null   float64
 7   wspdi            9744 non-null   float64
 8   wgustm           1876 non-null   float64
 9   wgusti           1876 non-null   float64
 10  wdird            10481 non-null  int64
 11  wdire            10481 non-null  object
 12  vism             10236 non-null  float64
 13  visi             10236 non-null  float64
 14  pressurem        10242 non-null  float64
 15  pressurei        10242 non-null  float64
 16  windchillm       2706 non-null   float64
 17  windchilli       2706 non-null   float64
 18  heatindexm       837 non-null    float64
 19  heatindexi       837 non-null    float64
 20  precipm          1706 non-null   float64
 21  precipi          1706 non-null   float64
 22  conds            10481 non-null  object
 23  icon             10481 non-null  object
 24  fog              10481 non-null  int64
 25  rain             10481 non-null  int64
 26  snow             10481 non-null  int64
 27  hail             10481 non-null  int64
 28  thunder          10481 non-null  int64
 29  tornado          10481 non-null  int64
dtypes: float64(19), int64(7), object(4)
memory usage: 2.4+ MB

#### membuat desimal 3 angka di belakang koma

In [47]:
df['rain'] = df['rain'].astype('float64')
pd.options.display.float_format = "{:,.3f}".format
print(df['rain'])

0       1.000
1       0.000
2       0.000
3       0.000
4       0.000
         ...
10476   0.000
10477   0.000
10478   0.000
10479   0.000
10480   0.000
Name: rain, Length: 10481, dtype: float64

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10481 entries, 0 to 10480
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup_datetime  10481 non-null  object
 1   tempm            10476 non-null  float64
 2   tempi            10476 non-null  float64
 3   dewptm           10476 non-null  float64
 4   dewpti           10476 non-null  float64
 5   hum              10476 non-null  float64
 6   wspdm            9744 non-null   float64
 7   wspdi            9744 non-null   float64
 8   wgustm           1876 non-null   float64
 9   wgusti           1876 non-null   float64
 10  wdird            10481 non-null  int64
 11  wdire            10481 non-null  object
 12  vism             10236 non-null  float64
 13  visi             10236 non-null  float64
 14  pressurem        10242 non-null  float64
 15  pressurei        10242 non-null  float64
 16  windchillm       2706 non-null   float64
 17  windchilli       2706 non-null   float64
 18  heatindexm       837 non-null    float64
 19  heatindexi       837 non-null    float64
 20  precipm          1706 non-null   float64
 21  precipi          1706 non-null   float64
 22  conds            10481 non-null  object
 23  icon             10481 non-null  object
 24  fog              10481 non-null  int64
 25  rain             10481 non-null  float64
 26  snow             10481 non-null  int64
 27  hail             10481 non-null  int64
 28  thunder          10481 non-null  int64
 29  tornado          10481 non-null  int64
dtypes: float64(20), int64(6), object(4)
memory usage: 2.4+ MB

#### tampilan desimal yang diubah

In [48]:
df.head(5)

,pickup_datetime,tempm,tempi,dewptm,dewpti,hum,wspdm,wspdi,wgustm,wgusti,...,precipm,precipi,conds,icon,fog,rain,snow,hail,thunder,tornado
0,2015-12-31 00:15:00,7.800,46.000,6.100,43.000,89.000,7.400,4.600,NaN,NaN,...,0.500,0.020,Light Rain,rain,0,1.000,0,0,0,0
1,2015-12-31 00:42:00,7.800,46.000,6.100,43.000,89.000,7.400,4.600,NaN,NaN,...,0.800,0.030,Overcast,cloudy,0,0.000,0,0,0,0
2,2015-12-31 00:51:00,7.800,46.000,6.100,43.000,89.000,5.600,3.500,NaN,NaN,...,0.800,0.030,Overcast,cloudy,0,0.000,0,0,0,0
3,2015-12-31 01:51:00,7.200,45.000,5.600,42.100,90.000,7.400,4.600,NaN,NaN,...,0.300,0.010,Overcast,cloudy,0,0.000,0,0,0,0
4,2015-12-31 02:51:00,7.200,45.000,5.600,42.100,90.000,0.000,0.000,NaN,NaN,...,NaN,NaN,Overcast,cloudy,0,0.000,0,0,0,0

#### Tampilkan 10 record pertama dari attribute bertipe angka

In [38]:
hasil = df.select_dtypes(include=np.number)

In [40]:
hasil.head(10)

,tempm,tempi,dewptm,dewpti,hum,wspdm,wspdi,wgustm,wgusti,wdird,...,heatindexm,heatindexi,precipm,precipi,fog,rain,snow,hail,thunder,tornado
0,7.8,46.0,6.1,43.0,89.0,7.4,4.6,NaN,NaN,40,...,NaN,NaN,0.5,0.02,0,1,0,0,0,0
1,7.8,46.0,6.1,43.0,89.0,7.4,4.6,NaN,NaN,0,...,NaN,NaN,0.8,0.03,0,0,0,0,0,0
2,7.8,46.0,6.1,43.0,89.0,5.6,3.5,NaN,NaN,20,...,NaN,NaN,0.8,0.03,0,0,0,0,0,0
3,7.2,45.0,5.6,42.1,90.0,7.4,4.6,NaN,NaN,0,...,NaN,NaN,0.3,0.01,0,0,0,0,0,0
4,7.2,45.0,5.6,42.1,90.0,0.0,0.0,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
5,6.7,44.1,5.0,41.0,89.0,7.4,4.6,NaN,NaN,300,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
6,7.2,45.0,5.0,41.0,86.0,0.0,0.0,NaN,NaN,0,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
7,7.2,45.0,5.0,41.0,86.0,7.4,4.6,NaN,NaN,310,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
8,7.2,45.0,5.0,41.0,86.0,5.6,3.5,NaN,NaN,280,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
9,7.2,45.0,5.6,42.1,90.0,5.6,3.5,NaN,NaN,270,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0

In [50]:
df[['pickup_datetime',
 'tempm',
 'tempi',
 'dewptm',
 'dewpti',
 'hum',
 'wspdm',
 'wspdi',
 'wgustm',
 'wgusti',
 'wdird',
 'wdire',
 'vism',
 'visi',
 'pressurem',
 'pressurei',
 'windchillm',
 'windchilli',
 'heatindexm',
 'heatindexi',
 'precipm',
 'precipi',
 'conds',
 'icon',
 'fog',
 'rain',
 'snow',
 'hail',
 'thunder',
 'tornado']].to_csv('tugas_fikri.csv', index=False)